version: '3.8'

services:
  app:
    build:
      context: ./api
    ports:
      - "2000:2000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGODB_URI}
    volumes:
      - ./api:/app
    command: nodemon .
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: